#!/usr/bin/env python3
"""
System Monitor Terminal Dashboard

Displays live system metrics in terminal using rich TUI.
Reads from existing JSON files generated by PowerShell/Bash monitoring scripts.
"""

import sys
import argparse
import logging
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent))

from display.tui_dashboard import SystemDashboard


def main():
    """Main entry point for the dashboard application."""
    parser = argparse.ArgumentParser(
        description="System Monitor Terminal Dashboard - Live system metrics visualization",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python dashboard_tui.py
  python dashboard_tui.py --metrics-path data/metrics/current.json
  python dashboard_tui.py --alerts-path data/alerts/alerts.json
  python dashboard_tui.py --verbose

Note: Press Ctrl+C to exit the dashboard.
        """
    )
    
    parser.add_argument(
        "--metrics-path",
        default="data/metrics/current.json",
        help="Path to metrics JSON file (default: data/metrics/current.json)"
    )
    
    parser.add_argument(
        "--alerts-path",
        default="data/alerts/alerts.json",
        help="Path to alerts JSON file (default: data/alerts/alerts.json)"
    )
    
    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="Enable verbose logging"
    )
    
    args = parser.parse_args()
    
    # Configure logging
    log_level = logging.DEBUG if args.verbose else logging.INFO
    logging.basicConfig(
        level=log_level,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
        handlers=[
            logging.FileHandler('data/logs/dashboard.log'),
            logging.StreamHandler() if args.verbose else logging.NullHandler()
        ]
    )
    
    logger = logging.getLogger(__name__)
    
    try:
        # Validate paths exist or can be created
        metrics_path = Path(args.metrics_path)
        alerts_path = Path(args.alerts_path)
        
        if not metrics_path.exists():
            logger.warning(f"Metrics file not found: {metrics_path}")
            print(f"⚠️  Warning: Metrics file not found: {metrics_path}")
            print("   Dashboard will show 'N/A' until metrics are available.")
            print()
        
        # Ensure alerts directory exists
        alerts_path.parent.mkdir(parents=True, exist_ok=True)
        
        # Create and run dashboard
        dashboard = SystemDashboard(args.metrics_path, args.alerts_path)
        
        print("Starting System Monitor Dashboard...")
        print("Press Ctrl+C to exit\n")
        
        dashboard.run()
        
    except FileNotFoundError as e:
        print(f"❌ Error: File not found - {e}")
        logger.error(f"File not found: {e}")
        sys.exit(1)
        
    except PermissionError as e:
        print(f"❌ Error: Permission denied - {e}")
        logger.error(f"Permission denied: {e}")
        sys.exit(1)
        
    except KeyboardInterrupt:
        print("\n✅ Dashboard stopped by user")
        logger.info("Dashboard stopped by user")
        sys.exit(0)
        
    except Exception as e:
        print(f"❌ Unexpected error: {e}")
        logger.error(f"Unexpected error: {e}", exc_info=True)
        sys.exit(1)


if __name__ == "__main__":
    main()
